-- ============================================================
-- Catálogo local expandido — plantas conhecidas com imagens
-- Rode depois de ajustes_supabase_final.sql e catalogo_local.sql.
-- Pode ser executado mais de uma vez sem duplicar registros.
-- As imagens são do Wikimedia Commons; veja ATTRIBUTIONS.md.
-- ============================================================

INSERT INTO plants (
  name, scientific_name, description, watering_frequency, light_requirement,
  light_intensity_min, light_intensity_max, ideal_temperature, humidity,
  toxicity_level, dangerous_to_dogs, dangerous_to_cats, dangerous_to_other,
  toxicity_symptoms, care_level, soil_type, fertilization, images
)
SELECT * FROM (VALUES
('Jiboia', 'Epipremnum aureum', 'Trepadeira de folhas verdes e variegadas, muito popular em ambientes internos e fácil de cultivar.', 'A cada 7-10 dias', 'Meia-sombra', 1000, 5000, '18°C a 30°C', 'Moderada', 'Baixa', true, true, false, 'Pode causar irritação se ingerida', 'Fácil', 'Solo leve e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Epipremnum_aureum_31082012.jpg/960px-Epipremnum_aureum_31082012.jpg']::text[]),
('Espada-de-são-jorge', 'Dracaena trifasciata', 'Planta resistente de folhas rígidas e verticais, muito usada em vasos e ambientes internos.', 'A cada 10-15 dias', 'Meia-sombra', 1000, 5000, '18°C a 30°C', 'Baixa', 'Baixa', true, true, false, 'Pode causar náusea e irritação se ingerida', 'Fácil', 'Solo arenoso e bem drenado', 'A cada 45 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Fleur_de_Sansevieria_01.jpg/960px-Fleur_de_Sansevieria_01.jpg']::text[]),
('Zamioculca', 'Zamioculcas zamiifolia', 'Planta de folhas brilhantes e muito resistente à falta de água, adequada para interiores.', 'A cada 10-15 dias', 'Sombra', 100, 1000, '18°C a 30°C', 'Baixa', 'Baixa', true, true, false, 'Pode causar irritação na boca', 'Fácil', 'Solo arenoso e bem drenado', 'A cada 45 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/ZZ_Plant_%28Zamioculcas_zamiifolia%29.jpg/960px-ZZ_Plant_%28Zamioculcas_zamiifolia%29.jpg']::text[]),
('Costela-de-adão', 'Monstera deliciosa', 'Planta tropical de folhas grandes recortadas, muito utilizada na decoração de interiores.', 'A cada 5-7 dias', 'Meia-sombra', 1000, 5000, '18°C a 30°C', 'Alta', 'Alta', true, true, false, 'Contém oxalato de cálcio e pode irritar boca e garganta', 'Médio', 'Solo rico em matéria orgânica e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/Monstera_deliciosa2.jpg/960px-Monstera_deliciosa2.jpg']::text[]),
('Samambaia', 'Nephrolepis exaltata', 'Planta de folhas longas e delicadas, apreciada em vasos suspensos e locais úmidos.', 'A cada 2-3 dias', 'Meia-sombra', 1000, 5000, '18°C a 26°C', 'Alta', 'Nenhuma', false, false, false, NULL, 'Médio', 'Solo úmido, rico e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Fern_20.jpg/960px-Fern_20.jpg']::text[]),
('Babosa', 'Aloe vera', 'Suculenta de folhas carnudas, conhecida pelo uso ornamental e pelas propriedades do gel das folhas.', 'A cada 10-15 dias', 'Sol pleno', 5000, 20000, '18°C a 30°C', 'Baixa', 'Baixa', true, true, false, 'Pode causar desconforto se ingerida', 'Fácil', 'Solo arenoso e muito bem drenado', 'A cada 60 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/Aloe_Vera_in_January._Madeira%2C_Portugal.jpg/960px-Aloe_Vera_in_January._Madeira%2C_Portugal.jpg']::text[]),
('Cacto', 'Cactaceae', 'Grupo de plantas suculentas adaptadas a ambientes secos, com grande variedade de formatos.', 'A cada 15-20 dias', 'Sol pleno', 10000, 20000, '18°C a 35°C', 'Baixa', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Substrato arenoso e muito bem drenado', 'A cada 60 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Copiapoa_serpentisulcata_%287302076184%29.jpg/960px-Copiapoa_serpentisulcata_%287302076184%29.jpg']::text[]),
('Echevéria', 'Echeveria spp.', 'Suculenta em formato de roseta, com folhas coloridas e baixa necessidade de rega.', 'A cada 10-15 dias', 'Sol pleno', 5000, 20000, '15°C a 30°C', 'Baixa', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Substrato para suculentas, bem drenado', 'A cada 60 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Echeveria_%27Topsy_Turvy%27_%28Echeveria_runyonii%29_1.jpg/960px-Echeveria_%27Topsy_Turvy%27_%28Echeveria_runyonii%29_1.jpg']::text[]),
('Ficus-lira', 'Ficus lyrata', 'Planta ornamental de folhas grandes em formato de lira, muito usada em ambientes internos iluminados.', 'A cada 7-10 dias', 'Luz indireta', 1000, 5000, '18°C a 30°C', 'Moderada', 'Baixa', true, true, false, 'Seiva pode irritar', 'Médio', 'Solo fértil e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Ficus_lyrata_393081768.jpg/960px-Ficus_lyrata_393081768.jpg']::text[]),
('Ficus-borracha', 'Ficus elastica', 'Planta de folhas largas e brilhantes, resistente e adequada para interiores bem iluminados.', 'A cada 7-10 dias', 'Luz indireta', 1000, 5000, '18°C a 30°C', 'Moderada', 'Baixa', true, true, false, 'Seiva pode irritar', 'Fácil', 'Solo rico e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Backlit_ficus_elastica_leaf_texture_2014_02.jpg/960px-Backlit_ficus_elastica_leaf_texture_2014_02.jpg']::text[]),
('Clorofito', 'Chlorophytum comosum', 'Planta de folhas finas e arqueadas, conhecida pela facilidade de cultivo e pelos brotos pendentes.', 'A cada 5-7 dias', 'Meia-sombra', 1000, 5000, '15°C a 28°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo leve e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Chlorophytum_comosum%2C_flores.jpg/960px-Chlorophytum_comosum%2C_flores.jpg']::text[]),
('Lírio-da-paz', 'Spathiphyllum wallisii', 'Planta de interior com folhas verdes e flores brancas, gosta de umidade e luz indireta.', 'A cada 4-5 dias', 'Meia-sombra', 1000, 5000, '18°C a 28°C', 'Alta', 'Alta', true, true, false, 'Contém oxalato de cálcio', 'Fácil', 'Solo rico, úmido e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/SpathiphyllumWallisii.jpg/960px-SpathiphyllumWallisii.jpg']::text[]),
('Maranta', 'Maranta leuconeura', 'Planta tropical de folhas estampadas que se movimentam ao longo do dia, ideal para luz indireta.', 'A cada 3-5 dias', 'Meia-sombra', 1000, 5000, '18°C a 27°C', 'Alta', 'Nenhuma', false, false, false, NULL, 'Médio', 'Solo úmido, leve e rico', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/2/21/Damaged_Lemon-Lime_Maranta_Leuconeura_or_Prayer_Plant_01.jpg/960px-Damaged_Lemon-Lime_Maranta_Leuconeura_or_Prayer_Plant_01.jpg']::text[]),
('Calatéia', 'Calathea spp.', 'Planta tropical de folhas decorativas, prefere umidade alta e luz indireta sem sol direto.', 'A cada 3-5 dias', 'Meia-sombra', 1000, 5000, '18°C a 27°C', 'Alta', 'Nenhuma', false, false, false, NULL, 'Médio', 'Solo úmido, leve e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Calathea_warscewiczii_-_Wilhelma.jpg/960px-Calathea_warscewiczii_-_Wilhelma.jpg']::text[]),
('Peperômia', 'Peperomia spp.', 'Planta compacta de folhas carnudas, indicada para vasos pequenos e ambientes internos claros.', 'A cada 7-10 dias', 'Luz indireta', 1000, 5000, '18°C a 28°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo leve e bem drenado', 'A cada 45 dias', ARRAY['https://upload.wikimedia.org/wikipedia/commons/7/7d/Peperomia_uaupesensis.jpg']::text[]),
('Pilea', 'Pilea peperomioides', 'Planta de folhas arredondadas, compacta e muito popular em coleções de plantas de interior.', 'A cada 7 dias', 'Luz indireta', 1000, 5000, '15°C a 25°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo leve e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f6/%28MHNT%29_Pilea_peperomioides_Foliage.jpg/960px-%28MHNT%29_Pilea_peperomioides_Foliage.jpg']::text[]),
('Violeta-africana', 'Saintpaulia ionantha', 'Planta pequena de flores delicadas, adequada para interiores iluminados sem sol direto.', 'A cada 5-7 dias', 'Luz indireta', 1000, 5000, '18°C a 24°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Médio', 'Substrato leve e bem drenado', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/African_violet_%28Saintpaulia%29.jpg/960px-African_violet_%28Saintpaulia%29.jpg']::text[]),
('Hortelã', 'Mentha spicata', 'Erva aromática de crescimento rápido, muito usada em vasos e hortas domésticas.', 'A cada 2-3 dias', 'Meia-sombra', 1000, 5000, '15°C a 28°C', 'Alta', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo fértil e úmido', 'A cada 30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ac/00_1984_Gr%C3%BCne_Minze_%28Mentha_Spicata%29_-_Schmetterling_%28Weissling%29.jpg/960px-00_1984_Gr%C3%BCne_Minze_%28Mentha_Spicata%29_-_Schmetterling_%28Weissling%29.jpg']::text[]),
('Alecrim', 'Salvia rosmarinus', 'Erva aromática mediterrânea de folhas perfumadas, gosta de sol e pouca água.', 'A cada 7-10 dias', 'Sol pleno', 5000, 20000, '15°C a 28°C', 'Baixa', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo arenoso e bem drenado', 'A cada 45 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Rosmarinus_officinalis_MHNT.BOT.2008.1.19.jpg/960px-Rosmarinus_officinalis_MHNT.BOT.2008.1.19.jpg']::text[]),
('Manjericão', 'Ocimum basilicum', 'Erva aromática de folhas perfumadas, cultivada em vasos, hortas e jardins ensolarados.', 'A cada 2-3 dias', 'Sol pleno', 5000, 20000, '18°C a 30°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo fértil e bem drenado', 'A cada 20-30 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Ocimum_Basilicum_leaf_lighted_by_the_left.jpg/960px-Ocimum_Basilicum_leaf_lighted_by_the_left.jpg']::text[]),
('Tomilho', 'Thymus vulgaris', 'Erva aromática de pequeno porte, resistente e adequada para vasos com bastante sol.', 'A cada 7 dias', 'Sol pleno', 5000, 20000, '15°C a 28°C', 'Baixa', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo arenoso e bem drenado', 'A cada 45 dias', ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Eristalinus_aeneus_on_Thymus_vulgaris%2C_S%C3%A8te_03.jpg/960px-Eristalinus_aeneus_on_Thymus_vulgaris%2C_S%C3%A8te_03.jpg']::text[])
) AS v(
  name, scientific_name, description, watering_frequency, light_requirement,
  light_intensity_min, light_intensity_max, ideal_temperature, humidity,
  toxicity_level, dangerous_to_dogs, dangerous_to_cats, dangerous_to_other,
  toxicity_symptoms, care_level, soil_type, fertilization, images
)
WHERE NOT EXISTS (SELECT 1 FROM plants p WHERE p.name = v.name);

-- Corrige as fotos das entradas antigas mais usadas que estavam sem imagem.
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Comestible_rose_in_the_Laquenexy_orchard_garden%2C_Moselle%2C_France_%2801%29.jpg/960px-Comestible_rose_in_the_Laquenexy_orchard_garden%2C_Moselle%2C_France_%2801%29.jpg']::text[] WHERE name = 'Rosa' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Phalaenopsis_cultivar_%28Moth_orchid%29.jpg/960px-Phalaenopsis_cultivar_%28Moth_orchid%29.jpg']::text[] WHERE name = 'Orquídea' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/African_violet_%28Saintpaulia%29.jpg/960px-African_violet_%28Saintpaulia%29.jpg']::text[] WHERE name = 'Violeta-africana' AND (images IS NULL OR cardinality(images) = 0);

-- Fotos para as 40 plantas da primeira versão do catálogo.
-- Só preenche quando a entrada ainda estiver sem imagem.
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Rosa_%27Surrey%27_%28actm%29_01.jpg/960px-Rosa_%27Surrey%27_%28actm%29_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Rosa' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Formosa_lily%2C_Nagai_Park%2C_Osaka.jpg/960px-Formosa_lily%2C_Nagai_Park%2C_Osaka.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Lírio' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Triumph_Tulip_Tulipa_%27Prinses_Irene%27_Single_2859px.jpg/960px-Triumph_Tulip_Tulipa_%27Prinses_Irene%27_Single_2859px.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Tulipa' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Bellis_perennis_full_plant.jpg/960px-Bellis_perennis_full_plant.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Margarida' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Sunflower_macro_wide.jpg/960px-Sunflower_macro_wide.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Girassol' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/%28MHNT%29_Dysmachus_trigonus_on_Dianthus_caryophyllus.jpg/960px-%28MHNT%29_Dysmachus_trigonus_on_Dianthus_caryophyllus.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Cravo' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Bigleaf_Hydrangea_Hydrangea_macrophylla_%27Tokyo_Delight%27_Flowers_3008px.jpg/960px-Bigleaf_Hydrangea_Hydrangea_macrophylla_%27Tokyo_Delight%27_Flowers_3008px.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Hortênsia' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Viola_odorata_sl3.jpg/960px-Viola_odorata_sl3.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Violeta' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Petunia_%C3%97_hybrida_-_Karlsruhe.jpg/960px-Petunia_%C3%97_hybrida_-_Karlsruhe.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Petúnia' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Begonia_grandis_%27claret_jug%27_01.jpg/960px-Begonia_grandis_%27claret_jug%27_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Begônia' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e9/Camellia_japonica_NBG.jpg/960px-Camellia_japonica_NBG.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Camélia' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/Rhododendron_simsii_01.JPG/960px-Rhododendron_simsii_01.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Azaleia' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e8/Lille_jardin_des_plantes_dahlias.jpg/960px-Lille_jardin_des_plantes_dahlias.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Dália' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Chrysantheme_rot_tautropfen_-20191024-RM-102058.jpg/960px-Chrysantheme_rot_tautropfen_-20191024-RM-102058.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Crisântemo' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Phalaenopsis_Cultivar_White_01.jpg/960px-Phalaenopsis_Cultivar_White_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Orquídea' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/%28MHNT%29_Jasminum_polyanthum_%E2%80%93_flowers_and_buds.jpg/960px-%28MHNT%29_Jasminum_polyanthum_%E2%80%93_flowers_and_buds.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Jasmim' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Vanessa_cardui_on_Lavandula_angustifolia-2459.jpg/960px-Vanessa_cardui_on_Lavandula_angustifolia-2459.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Lavanda' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Hibiscus_petal.jpg/960px-Hibiscus_petal.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Hibisco' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/D%C3%BClmen%2C_Fr%C3%B6belstra%C3%9Fe%2C_Mohn_am_Feldrand_--_2021_--_9174.jpg/960px-D%C3%BClmen%2C_Fr%C3%B6belstra%C3%9Fe%2C_Mohn_am_Feldrand_--_2021_--_9174.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Papoula' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/Paeonia_rockii_2013_G1.jpg/960px-Paeonia_rockii_2013_G1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Peônia' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/Anthurium_%28Flamingoplant%29_12-08-2019_%28actm%29_01.jpg/960px-Anthurium_%28Flamingoplant%29_12-08-2019_%28actm%29_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Antúrio' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8d/Calla_lily_%28Zantedeschia_aethiopica%29%2C_Parque_do_Monteiro-Mor%2C_Lisbon%2C_Portugal_julesvernex2.jpg/960px-Calla_lily_%28Zantedeschia_aethiopica%29%2C_Parque_do_Monteiro-Mor%2C_Lisbon%2C_Portugal_julesvernex2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Copo-de-leite' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/7/71/Aechmea_nudicaulis%2C_jard%C3%ADn_bot%C3%A1nico_de_Tallinn%2C_Estonia%2C_2012-08-13%2C_DD_01.JPG/960px-Aechmea_nudicaulis%2C_jard%C3%ADn_bot%C3%A1nico_de_Tallinn%2C_Estonia%2C_2012-08-13%2C_DD_01.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Bromélia' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/Viola_tricolor_Fio%C5%82ek_tr%C3%B3jbarwny_2022-06-29_03.jpg/960px-Viola_tricolor_Fio%C5%82ek_tr%C3%B3jbarwny_2022-06-29_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Amor-perfeito' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Antirrhinum_majus_F1_%27Rocket_Orchid%27.jpg/960px-Antirrhinum_majus_F1_%27Rocket_Orchid%27.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Boca-de-leão' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Bloeiwijze_van_Verbena_bonariensis._07-09-2024._%28d.j.b%29.jpg/960px-Bloeiwijze_van_Verbena_bonariensis._07-09-2024._%28d.j.b%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Verbena' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/Bougainvillea_spectabilis_01.JPG/960px-Bougainvillea_spectabilis_01.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Primavera' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://upload.wikimedia.org/wikipedia/commons/c/ca/Ipe-amarelo_curitiba.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled']::text[] WHERE name = 'Ipê-amarelo' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d6/Flame_tree_mali.jpg/960px-Flame_tree_mali.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Flamboyant' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Agapanthus_%27White_Heaven%27%2C_ingetogen_schoonheid_van_de_ontluikende_bloemknop._Locatie%2C_Tuinreservaat_Jonkervallei_03.jpg/960px-Agapanthus_%27White_Heaven%27%2C_ingetogen_schoonheid_van_de_ontluikende_bloemknop._Locatie%2C_Tuinreservaat_Jonkervallei_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Agapanto' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Eustoma_grandiflorum-hrs-yercaud-salem-India.JPG/960px-Eustoma_grandiflorum-hrs-yercaud-salem-India.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Lisianto' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/BarbertonDaisy.jpg/960px-BarbertonDaisy.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Gérbera' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Zinnia_elegans_with_Bombus_01.JPG/960px-Zinnia_elegans_with_Bombus_01.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Zínia' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Zaaddoos_van_een_goudsbloem_%28Calendula_officinalis%29_11-09-2020_%28d.j.b.%29.jpg/960px-Zaaddoos_van_een_goudsbloem_%28Calendula_officinalis%29_11-09-2020_%28d.j.b.%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Calêndula' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Cosmos_bipinnatus_Bl%C3%BCte-20230819-RM-123333.jpg/960px-Cosmos_bipinnatus_Bl%C3%BCte-20230819-RM-123333.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Cosmos' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Amaryllis_%28Hippeastrum%29_18-01-2025._%28actm.%29_04.jpg/960px-Amaryllis_%28Hippeastrum%29_18-01-2025._%28actm.%29_04.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Amarílis' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Narcissus_%27Ice_Follies%27_02.jpg/960px-Narcissus_%27Ice_Follies%27_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Narciso' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Garden_Hyacinth_Hyacinthus_orientalis_%27Purple_Voice%27_Flower_1644px.JPG/960px-Garden_Hyacinth_Hyacinthus_orientalis_%27Purple_Voice%27_Flower_1644px.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Jacinto' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/African_violets_photo_test.jpg/960px-African_violets_photo_test.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail']::text[] WHERE name = 'Violeta-africana' AND (images IS NULL OR cardinality(images) = 0);
UPDATE plants SET images = ARRAY['https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/Staande_geranium_Pelargonium_zonale_wit._20-06-2025._%28actm.%29_02.jpg/960px-Staande_geranium_Pelargonium_zonale_wit._20-06-2025._%28actm.%29_02.jpg']::text[] WHERE name = 'Gerânio' AND (images IS NULL OR cardinality(images) = 0);
