-- ============================================================
-- Catálogo local de flores/plantas comuns (fallback)
-- Reaproveita a tabela "plants" que já existe no projeto.
-- Usado quando a Perenual não encontra a planta buscada —
-- cobre espécies famosas que o plano gratuito da Perenual não tem
-- (ela só libera as primeiras ~3.000 de +10.000 espécies).
-- Rode no SQL Editor do Supabase. Pode rodar mais de uma vez sem
-- duplicar (verifica pelo nome antes de inserir).
-- ============================================================

INSERT INTO plants (
  name, scientific_name, description, watering_frequency, light_requirement,
  light_intensity_min, light_intensity_max, ideal_temperature, humidity,
  toxicity_level, dangerous_to_dogs, dangerous_to_cats, dangerous_to_other,
  toxicity_symptoms, care_level, soil_type, fertilization, images
)
SELECT * FROM (VALUES
('Rosa', 'Rosa spp.', 'Arbusto florífero cultivado em jardins no mundo todo, símbolo clássico de beleza e romance, com centenas de variedades de cor e porte.', 'A cada 2-3 dias', 'Sol pleno', 5000, 20000, '15°C a 25°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Médio', 'Solo rico, bem drenado, levemente ácido', 'A cada 30 dias na primavera e verão', ARRAY[]::text[]),
('Lírio', 'Lilium spp.', 'Flor elegante de pétalas grandes e perfume marcante, muito usada em jardins e buquês.', 'A cada 3-4 dias', 'Meia-sombra', 1000, 5000, '15°C a 24°C', 'Moderada', 'Alta', false, true, false, 'Muito tóxico para gatos; pode causar insuficiência renal', 'Médio', 'Solo fértil e bem drenado', 'A cada 30 dias durante o crescimento', ARRAY[]::text[]),
('Tulipa', 'Tulipa spp.', 'Flor de bulbo típica de jardins de primavera, com pétalas em formato de taça e cores vivas.', 'A cada 4-5 dias', 'Sol pleno', 5000, 20000, '10°C a 20°C', 'Moderada', 'Baixa', true, true, false, 'Pode causar irritação se ingerida em grande quantidade', 'Médio', 'Solo bem drenado, arenoso', 'Uma vez no plantio do bulbo', ARRAY[]::text[]),
('Margarida', 'Bellis perennis', 'Flor pequena e simples, de pétalas brancas e centro amarelo, símbolo de simplicidade.', 'A cada 3-4 dias', 'Sol pleno', 5000, 20000, '15°C a 24°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo comum, bem drenado', 'A cada 30-45 dias', ARRAY[]::text[]),
('Girassol', 'Helianthus annuus', 'Planta alta e vistosa que acompanha o movimento do sol, com flores grandes e amarelas.', 'A cada 2-3 dias', 'Sol pleno', 10000, 20000, '18°C a 30°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo fértil e bem drenado', 'A cada 20-30 dias', ARRAY[]::text[]),
('Cravo', 'Dianthus caryophyllus', 'Flor de pétalas franjadas e perfume adocicado, clássica em buquês e arranjos.', 'A cada 3-4 dias', 'Sol pleno', 5000, 20000, '15°C a 24°C', 'Moderada', 'Baixa', true, true, false, 'Pode causar leve irritação gastrointestinal', 'Fácil', 'Solo bem drenado, levemente alcalino', 'A cada 30 dias', ARRAY[]::text[]),
('Hortênsia', 'Hydrangea macrophylla', 'Arbusto de flores em grandes cachos esféricos, cuja cor pode variar com o pH do solo.', 'A cada 2 dias', 'Meia-sombra', 1000, 5000, '15°C a 22°C', 'Alta', 'Baixa', true, true, false, 'Pode causar mal-estar gastrointestinal se ingerida', 'Médio', 'Solo úmido e rico em matéria orgânica', 'A cada 30 dias na primavera e verão', ARRAY[]::text[]),
('Violeta', 'Viola odorata', 'Pequena planta de flores roxas perfumadas, tradicional em jardins sombreados.', 'A cada 3-4 dias', 'Meia-sombra', 1000, 5000, '15°C a 22°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo úmido e bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Petúnia', 'Petunia × hybrida', 'Planta de floração abundante, muito usada em vasos e jardineiras por suas cores vibrantes.', 'A cada 2-3 dias', 'Sol pleno', 5000, 20000, '18°C a 28°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo leve e bem drenado', 'A cada 15-20 dias', ARRAY[]::text[]),
('Begônia', 'Begonia spp.', 'Planta ornamental de folhas decorativas e flores delicadas, popular em interiores e varandas.', 'A cada 3-4 dias', 'Meia-sombra', 1000, 5000, '18°C a 24°C', 'Alta', 'Baixa', true, true, false, 'Pode irritar a boca e o estômago', 'Médio', 'Solo rico e bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Gerânio', 'Pelargonium spp.', 'Planta de flores vistosas em tons de vermelho, rosa e branco, comum em jardineiras.', 'A cada 4-5 dias', 'Sol pleno', 5000, 20000, '15°C a 25°C', 'Baixa', 'Baixa', true, true, false, 'Pode causar irritação leve em animais', 'Fácil', 'Solo bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Camélia', 'Camellia japonica', 'Arbusto elegante de flores grandes e cerosas, muito apreciado em jardins clássicos.', 'A cada 3 dias', 'Meia-sombra', 1000, 5000, '12°C a 22°C', 'Alta', 'Nenhuma', false, false, false, NULL, 'Médio', 'Solo ácido, rico em matéria orgânica', 'A cada 45 dias', ARRAY[]::text[]),
('Azaleia', 'Rhododendron simsii', 'Arbusto de floração intensa e colorida, símbolo tradicional da primavera.', 'A cada 2-3 dias', 'Meia-sombra', 1000, 5000, '12°C a 20°C', 'Alta', 'Alta', true, true, false, 'Tóxica se ingerida — pode afetar o coração', 'Médio', 'Solo ácido e bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Dália', 'Dahlia spp.', 'Flor de bulbo com pétalas numerosas e simétricas, disponível em diversas formas e cores.', 'A cada 3 dias', 'Sol pleno', 5000, 20000, '15°C a 25°C', 'Moderada', 'Baixa', true, true, false, 'Pode causar irritação leve', 'Médio', 'Solo fértil e bem drenado', 'A cada 20-30 dias', ARRAY[]::text[]),
('Crisântemo', 'Chrysanthemum spp.', 'Flor tradicional de outono, com pétalas densas e grande variedade de cores.', 'A cada 3 dias', 'Sol pleno', 5000, 20000, '15°C a 24°C', 'Moderada', 'Baixa', true, true, false, 'Pode causar irritação de pele e estômago', 'Fácil', 'Solo bem drenado', 'A cada 20 dias', ARRAY[]::text[]),
('Orquídea', 'Orchidaceae (ex: Phalaenopsis)', 'Planta exótica e elegante, uma das famílias de flores mais apreciadas no mundo.', 'A cada 7 dias', 'Meia-sombra', 1000, 5000, '18°C a 26°C', 'Alta', 'Nenhuma', false, false, false, NULL, 'Médio', 'Substrato próprio para orquídeas (casca de pinus)', 'A cada 15 dias com adubo específico', ARRAY[]::text[]),
('Jasmim', 'Jasminum spp.', 'Trepadeira ou arbusto de flores brancas muito perfumadas, floresce principalmente à noite.', 'A cada 3-4 dias', 'Sol pleno', 5000, 20000, '15°C a 28°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Lavanda', 'Lavandula angustifolia', 'Planta aromática de flores roxas, usada em jardins, perfumaria e culinária.', 'A cada 7-10 dias', 'Sol pleno', 5000, 20000, '15°C a 25°C', 'Baixa', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo arenoso e bem drenado', 'A cada 45-60 dias', ARRAY[]::text[]),
('Hibisco', 'Hibiscus rosa-sinensis', 'Arbusto tropical de flores grandes e vistosas, muito comum em jardins e cercas-vivas.', 'A cada 2-3 dias', 'Sol pleno', 5000, 20000, '18°C a 30°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo fértil e bem drenado', 'A cada 20-30 dias', ARRAY[]::text[]),
('Papoula', 'Papaver rhoeas', 'Flor silvestre de pétalas finas e vermelhas, símbolo de memória em muitas culturas.', 'A cada 4-5 dias', 'Sol pleno', 5000, 20000, '15°C a 24°C', 'Baixa', 'Moderada', true, true, false, 'Partes da planta contêm alcaloides tóxicos', 'Fácil', 'Solo bem drenado', 'Dispensa adubação frequente', ARRAY[]::text[]),
('Peônia', 'Paeonia lactiflora', 'Flor grande e perfumada, muito valorizada em jardins e arranjos de casamento.', 'A cada 3-4 dias', 'Sol pleno', 5000, 20000, '10°C a 22°C', 'Moderada', 'Baixa', true, true, false, 'Pode causar leve irritação gastrointestinal', 'Médio', 'Solo rico e bem drenado', 'A cada 45 dias', ARRAY[]::text[]),
('Antúrio', 'Anthurium andraeanum', 'Planta tropical de flor brilhante em formato de coração, popular como planta de interior.', 'A cada 4-5 dias', 'Meia-sombra', 1000, 5000, '18°C a 27°C', 'Alta', 'Alta', true, true, true, 'Contém oxalato de cálcio, irrita boca e garganta', 'Médio', 'Solo rico em matéria orgânica, bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Copo-de-leite', 'Zantedeschia aethiopica', 'Planta elegante de flor branca em formato de funil, comum em jardins úmidos.', 'A cada 2 dias', 'Meia-sombra', 1000, 5000, '15°C a 24°C', 'Alta', 'Alta', true, true, true, 'Contém oxalato de cálcio, tóxica se ingerida', 'Médio', 'Solo úmido e rico', 'A cada 30 dias', ARRAY[]::text[]),
('Bromélia', 'Bromeliaceae', 'Planta tropical de folhas dispostas em roseta, muito usada em paisagismo e vasos.', 'A cada 5-7 dias (regar o centro da roseta)', 'Meia-sombra', 1000, 5000, '18°C a 28°C', 'Alta', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Substrato leve e bem drenado', 'A cada 45 dias', ARRAY[]::text[]),
('Amor-perfeito', 'Viola × wittrockiana', 'Pequena flor de pétalas coloridas e marcantes, muito usada em canteiros de inverno.', 'A cada 3 dias', 'Sol pleno', 5000, 20000, '10°C a 20°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo fértil e bem drenado', 'A cada 20-30 dias', ARRAY[]::text[]),
('Boca-de-leão', 'Antirrhinum majus', 'Flor alta e colorida cujas pétalas lembram a boca de um leão quando apertadas.', 'A cada 3-4 dias', 'Sol pleno', 5000, 20000, '15°C a 24°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Verbena', 'Verbena × hybrida', 'Planta de floração abundante em pequenos cachos coloridos, ótima para jardineiras.', 'A cada 3-4 dias', 'Sol pleno', 5000, 20000, '18°C a 28°C', 'Baixa', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Primavera', 'Bougainvillea spp.', 'Trepadeira vigorosa de brácteas coloridas (rosa, laranja, roxo), muito usada em muros e pérgolas.', 'A cada 5-7 dias', 'Sol pleno', 5000, 20000, '18°C a 30°C', 'Baixa', 'Baixa', true, true, false, 'Seiva pode irritar a pele', 'Fácil', 'Solo bem drenado', 'A cada 45 dias', ARRAY[]::text[]),
('Ipê-amarelo', 'Handroanthus albus', 'Árvore nativa brasileira que floresce intensamente em amarelo no fim do inverno.', 'A cada 7 dias (planta jovem)', 'Sol pleno', 5000, 20000, '18°C a 30°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo fértil e bem drenado', 'A cada 60 dias (planta jovem)', ARRAY[]::text[]),
('Flamboyant', 'Delonix regia', 'Árvore tropical de copa larga e flores vermelho-alaranjadas vibrantes.', 'A cada 7 dias (planta jovem)', 'Sol pleno', 5000, 20000, '20°C a 32°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo bem drenado', 'A cada 60 dias (planta jovem)', ARRAY[]::text[]),
('Agapanto', 'Agapanthus africanus', 'Planta de flores azuis ou brancas reunidas em grandes umbelas sobre hastes altas.', 'A cada 5 dias', 'Sol pleno', 5000, 20000, '15°C a 26°C', 'Moderada', 'Baixa', true, true, false, 'Seiva pode irritar a pele e mucosas', 'Fácil', 'Solo bem drenado', 'A cada 45 dias', ARRAY[]::text[]),
('Lisianto', 'Eustoma grandiflorum', 'Flor delicada parecida com uma rosa, muito usada em buquês de casamento.', 'A cada 3-4 dias', 'Sol pleno', 5000, 20000, '18°C a 24°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Médio', 'Solo bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Gérbera', 'Gerbera jamesonii', 'Flor de pétalas longas e coloridas ao redor de um centro escuro, muito usada em vasos.', 'A cada 3 dias', 'Sol pleno', 5000, 20000, '18°C a 26°C', 'Moderada', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo leve e bem drenado', 'A cada 20-30 dias', ARRAY[]::text[]),
('Zínia', 'Zinnia elegans', 'Flor de cores vivas e floração contínua durante todo o verão.', 'A cada 3 dias', 'Sol pleno', 5000, 20000, '18°C a 28°C', 'Baixa', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Calêndula', 'Calendula officinalis', 'Flor alaranjada de uso ornamental e também medicinal, de fácil cultivo.', 'A cada 3-4 dias', 'Sol pleno', 5000, 20000, '15°C a 24°C', 'Baixa', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo comum, bem drenado', 'A cada 30 dias', ARRAY[]::text[]),
('Cosmos', 'Cosmos bipinnatus', 'Flor delicada de pétalas finas, muito usada em jardins naturais e de borboletas.', 'A cada 4-5 dias', 'Sol pleno', 5000, 20000, '18°C a 28°C', 'Baixa', 'Nenhuma', false, false, false, NULL, 'Fácil', 'Solo bem drenado, pouco fértil', 'Dispensa adubação frequente', ARRAY[]::text[]),
('Amarílis', 'Hippeastrum spp.', 'Planta de bulbo com flores grandes em formato de trombeta, em tons vivos de vermelho e rosa.', 'A cada 5 dias', 'Sol pleno', 5000, 20000, '18°C a 25°C', 'Moderada', 'Alta', true, true, false, 'Tóxica para cães e gatos se ingerida', 'Fácil', 'Solo rico e bem drenado', 'A cada 30 dias durante o crescimento', ARRAY[]::text[]),
('Narciso', 'Narcissus spp.', 'Flor de bulbo amarela ou branca, uma das primeiras a florescer na primavera.', 'A cada 5-7 dias', 'Sol pleno', 5000, 20000, '10°C a 20°C', 'Moderada', 'Alta', true, true, false, 'Bulbo é tóxico se ingerido', 'Fácil', 'Solo bem drenado', 'Uma vez no plantio do bulbo', ARRAY[]::text[]),
('Jacinto', 'Hyacinthus orientalis', 'Flor de bulbo muito perfumada, com pequenas flores densas ao longo da haste.', 'A cada 5-7 dias', 'Sol pleno', 5000, 20000, '10°C a 20°C', 'Moderada', 'Moderada', true, true, false, 'Bulbo pode causar irritação se manuseado ou ingerido', 'Fácil', 'Solo bem drenado', 'Uma vez no plantio do bulbo', ARRAY[]::text[]),
('Violeta-africana', 'Saintpaulia ionantha', 'Pequena planta de interior com flores roxas, rosas ou brancas sobre folhas aveludadas.', 'A cada 5-7 dias', 'Meia-sombra', 1000, 5000, '18°C a 24°C', 'Alta', 'Nenhuma', false, false, false, NULL, 'Médio', 'Substrato leve e bem drenado', 'A cada 30 dias', ARRAY[]::text[])
) AS v(
  name, scientific_name, description, watering_frequency, light_requirement,
  light_intensity_min, light_intensity_max, ideal_temperature, humidity,
  toxicity_level, dangerous_to_dogs, dangerous_to_cats, dangerous_to_other,
  toxicity_symptoms, care_level, soil_type, fertilization, images
)
WHERE NOT EXISTS (SELECT 1 FROM plants p WHERE p.name = v.name);
